services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - MAINTENANCE_MODE=${MAINTENANCE_MODE:-false}
    container_name: brutalist-portfolio
    ports:
      - "${APP_PORT:-80}:80"
      - "443:443"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - portfolio-network
    volumes:
      # - ./ssl:/etc/nginx/ssl:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    labels:
      - "com.docker.compose.project=brutalist-portfolio"

networks:
  portfolio-network:
    driver: bridge
